CREATE TABLE USUARIO(
	Id_Usuario INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Usuario VARCHAR(50) NOT NULL,
	Tipo_Usr VARCHAR(50) NOT NULL,
	Nacimiento VARCHAR(50) NOT NULL,
	Pass VARCHAR(50)NOT NULL
);


CREATE TABLE BITACORA(
	Id_bitacora INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Fecha Date NOT NULL,
	Usuario VARCHAR(50) NOT NULL,
	IpU VARCHAR(50) NOT NULL,
	Accion VARCHAR(50)NOT NULL
);

INSERT INTO USUARIO  VALUES ('Nickte','Adriana', 'admin1','1','10022000', '123')
INSERT INTO USUARIO  VALUES ('Luis','De Leon', 'admin2','1','10022000', '321')
INSERT INTO USUARIO  VALUES ('Jose','De Leon', 'admin3','1','10022000', 'jose25')
INSERT INTO USUARIO  VALUES ('Jose','Perez', 'joseperez','2','15031999', 'jose123')

SELECT * FROM USUARIO
SELECT * FROM BITACORA