CREATE TABLE USUARIO(
	Id_Usuario INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Usuario VARCHAR(50) NOT NULL,
	Tipo_Usr VARCHAR(50) NOT NULL,
	Nacimiento DATE NOT NULL,
	Pass VARCHAR(50)NOT NULL
);


CREATE TABLE BITACORA(
	Id_bitacora INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Fecha Date NOT NULL,
	Usuario VARCHAR(50) NOT NULL,
	IpU VARCHAR(50) NOT NULL,
	Accion VARCHAR(50)NOT NULL
);

INSERT INTO USUARIO  VALUES ('Nickte','Adriana', 'admin','1','10022000', '123')


